---
title: "Análisis de la Producción científica de la UCLA"
author: "Sebastian Robledo"
date: "1/25/2022"
output: 
  html_document:
            toc: TRUE
            toc_float: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE, echo=FALSE}
library(tidyverse)
library(tidygraph)
library(igraph)
library(DT)
library(visNetwork)
library(ggraph)
```

```{r message=FALSE, warning=FALSE, echo=FALSE}
papers <- 
  read_csv("https://docs.google.com/spreadsheets/d/17b_d24WF2dRBedatAqgArWodAaAn6-o0/export?format=csv&gid=1924642330") |> 
  filter(ano > 2014)

researchers <- 
  read_csv("https://docs.google.com/spreadsheets/d/17b_d24WF2dRBedatAqgArWodAaAn6-o0/export?format=csv&gid=1531675683")
```

# Red Social Académica

Creamos la red social y revisamos sus características

```{r, echo=FALSE}
authors_sep <-  papers |> 
  select(id, autores) |> 
  separate_rows(autores, sep = ", ")
```

```{r, echo=FALSE}
authors_isolated <- 
  authors_sep |> 
  count(id) |> 
  filter(n == 1) |> 
  select(id) |> 
  pull()

authors_ASN <- 
  authors_sep |> 
  filter(!(id %in% authors_isolated))

id_list <- authors_ASN |> 
  select(id) |> 
  pull()

authors_edgelist <- tibble()

for (i in id_list) {
  df_1 = authors_ASN |> filter(id == i)
  df_2 = combn(df_1 |> select(autores) |> pull(), 2, simplify = FALSE)
  df_3 = data.frame(t(data.frame(df_2)), i)
  colnames(df_3) = c("Source", "Target", "id")
  authors_edgelist = authors_edgelist |> bind_rows(df_3)
  
}

authors_graph_tbl <- 
  graph_from_data_frame(authors_edgelist,directed = FALSE) |> 
  tidygraph::as_tbl_graph()
```

```{r, echo=FALSE}
researchers_ucla <- 
  researchers |> 
  select(integrantes, grupo) |> 
  mutate(universidad = "ucla")

authors_graph_tbl_1 <- 
  authors_graph_tbl |> 
  activate(nodes) |> 
  left_join(researchers_ucla, 
            by = c("name" = "integrantes")) |>
  mutate(universidad = if_else(is.na(universidad), "otra", universidad),
         grupo = if_else(is.na(grupo), "Sin_grupo", grupo)) 

authors_graph_tbl_ucla <- 
  authors_graph_tbl_1 |> 
  activate(nodes) |> 
  filter(universidad == "ucla")
```

Visualización de la red social académica entre los profesores de la U. Solo los profesores que están conectados.

```{r, echo=FALSE}
authors_graph_tbl_ucla_gc <- 
  authors_graph_tbl_ucla |> 
  activate(nodes) |> 
  mutate(components = group_components(type = "weak")) |> 
  filter(components == 1) 
  # ggraph(layout = "kk") +
  # geom_edge_link() +
  # geom_node_point()
```

```{r, echo=FALSE}
nodes <- 
  authors_graph_tbl_ucla_gc |> 
  activate(nodes) |>
  mutate(id = row_number()) |> 
  data.frame() |> 
  rename(label = name)

edges <- 
  authors_graph_tbl_ucla_gc |> 
  activate(edges) |> 
  data.frame() |> 
  group_by(from, to) |> 
  count(id) |> 
  select(-id) |> 
  distinct()

visNetwork(nodes = nodes, edges = edges, height = "500px") |> 
  visIgraphLayout(layout = "layout_with_fr") |> 
  visOptions(highlightNearest = TRUE, selectedBy = "label" ) |> 
  visInteraction(navigationButtons = TRUE, multiselect = TRUE)
```


# Most productive Researchers

This analyses is between 2016 and 2021. We want to see quality

```{r, echo=FALSE}
researchers_1 <-  
  researchers |> 
  select(integrantes, grupo)


papers_1 <- # We need to split autores from papers
  papers |> 
  select(grupo,
         categoria_revista, 
         SJR_Q , 
         ano, 
         autores) |> 
  separate_rows(autores, sep = ", ") |>  # Separate researchers 
  select(grupo,
         integrantes = autores, 
         ano, 
         categoria_revista, 
         SJR_Q)
```

### Publindex production

```{r, echo=FALSE}
paper_publindex <- 
  researchers_1 |> 
  left_join(papers_1, by = c("integrantes" = "integrantes", 
                             "grupo" = "grupo")) |> 
  select(integrantes,
         ano, 
         categoria_revista) |> 
  group_by(integrantes, 
           ano) |> 
  count(categoria_revista) |> 
  pivot_wider(names_from = categoria_revista, 
              values_from = n) |> 
  replace_na(list(A1 = 0, 
                  A2 = 0, 
                  C = 0, 
                  "Sin categoria" = 0, 
                  B = 0)) |> 
  select(integrantes, ano, A1, A2, B, C, "Sin categoria") |> 
  arrange(desc(A1))

paper_publindex |> 
  DT::datatable(class = "cell-border stripe", 
                rownames = F, 
                filter = "top", 
                editable = TRUE, 
                extensions = "Buttons", 
                options = list(dom = "Bfrtip",
                               buttons = c("copy",
                                           "csv",
                                           "excel", 
                                           "pdf", 
                                           "print")))
```

### Scimago production

```{r, echo=FALSE}
paper_scimago <- 
researchers_1 |> 
left_join(papers_1, by = c("integrantes" = "integrantes", 
"grupo" = "grupo")) |> 
select(integrantes,
ano, 
SJR_Q) |> 
group_by(integrantes, 
ano) |> 
count(SJR_Q) |>
na.omit() |> 
pivot_wider(names_from = SJR_Q, 
values_from = n) |> 
replace_na(list(Q1 = 0, 
Q2 = 0, 
Q3 = 0, 
"Sin categoria" = 0, 
Q4 = 0)) |> 
select(integrantes, ano, Q1, Q2, Q3, Q4, "Sin categoria") |> 
arrange(desc(Q1))

paper_scimago |> 
DT::datatable(class = "cell-border stripe", 
rownames = F, 
filter = "top", 
editable = TRUE, 
extensions = "Buttons", 
options = list(dom = "Bfrtip",
buttons = c("copy",
"csv",
"excel", 
"pdf", 
"print")))
```
